#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : es                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                         # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/icon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : MyChurros                                 # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : 0.99€                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : The official churreo app

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Free Daygame                                
your_link                                 : https://emilbaehr.com                     
your_city                                 :                            
email_address                             : freedaygame@outlook.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  # - title                                 : GitHub Pages Jekyll Theme
  #   description                           : Designed for GitHub Pages. Fork. Edit _config.yml. Upload screenshot/video. Push to gh-pages branch. Voilá!
  #   fontawesome_icon_name                 : magic
    
  - title                                 : Track your activity
    description                           : Keep track of your activity with very little effort. It takes 10 seconds to introduce a new entry.
    fontawesome_icon_name                 : magic

  - title                                 : See your growth
    description                           : Spot your strong and weak points using the statistics. We automatically calculate relevant statistics out of your activity data and present it to you in our beautiful charts so you can show off to your wings.
    fontawesome_icon_name                 : signal

  - title                                 : Keep it private
    description                           : Any information you introduce in MyChurros is stored locally in your phone. No annoying logins, no need for internet connection, you are the only owner of your data.
    fontawesome_icon_name                 : lock

  - title                                 : Use your data
    description                           : You can export or import your database using CSV files. Use MyChurros to keep track of your activity, export to CSV and use your data in your own spreadsheets.
    fontawesome_icon_name                 : star
  
  # - title                                 : Feature List
  #   description                           : Add features (like this one) to your site via the _config.yml file. No HTML/CSS needed.
  #   fontawesome_icon_name                 : adjust

  # - title                                 : Smart App Banner
  #   description                           : Display a smart app banner on iOS devices.
  #   fontawesome_icon_name                 : arrow-alt-circle-down

  # - title                                 : Social Links
  #   description                           : Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
  #   fontawesome_icon_name                 : link

  # - title                                 : FontAwesome Support
  #   description                           : Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
  #   fontawesome_icon_name                 : info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#a12bcc"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#a12bcc"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
